[package]

name = "qmlrs"
version = "0.0.1"
authors = ["Mikko Perttunen <cyndis@kapsi.fi>"]
license = "MIT/Apache-2.0"

build = "build.rs"

[dependencies]
libc = "*"

[build-dependencies.pkg-config]
git = "https://github.com/alexcrichton/pkg-config-rs"
